export const mockUsers = [
   {
      id: 1,
      username: 'admin',
      email: 'admin@mail.ru',
      password: '123',
      role: 'admin',
      bio: 'Главный администратор платформы',
      avatar: null,
      followers: [2],
      following: [3],
      completedSkills: [101],
      createdAt: '2026-01-01T10:00:00Z',
   },
   {
      id: 2,
      username: 'matvey_rts',
      email: 'mat@mail.ru',
      password: 'mat',
      role: 'user',
      bio: 'Дизайнер интерфейсов',
      avatar: null,
      followers: [],
      following: [1],
      completedSkills: [],
      createdAt: '2026-02-15T08:30:00Z',
   },
   {
      id: 3,
      username: 'alexsey_dem',
      email: 'alex@mail.ru',
      password: 'alex',
      role: 'user',
      bio: 'Люблю программировать и изучать новое',
      avatar: null,
      followers: [1],
      following: [],
      completedSkills: [102],
      createdAt: '2026-03-20T14:15:00Z',
   },
];

export const mockSkills = [
   {
      id: 1,
      title: 'React Basics',
      description: 'Изучите основы React: компоненты, состояние, хуки.',
      authorId: 1,
      createdAt: '2026-01-10T12:00:00Z',
      views: 1250,
      questions: [
         {
            id: 1,
            text: 'Что такое JSX?',
            options: ['Расширение синтаксиса JavaScript', 'Язык программирования', 'Библиотека', 'Фреймворк'],
            correct: 0,
         },
         {
            id: 2,
            text: 'Как называется хук для управления состоянием?',
            options: ['useEffect', 'useState', 'useContext', 'useReducer'],
            correct: 1,
         },
      ],
      attempts: [{ userId: 2, score: 1, date: '2026-03-01' }],
   },
   {
      id: 2,
      title: 'UI/UX Fundamentals',
      description: 'Основы проектирования пользовательских интерфейсов.',
      authorId: 3,
      createdAt: '2026-02-20T09:00:00Z',
      views: 890,
      questions: [
         {
            id: 1,
            text: 'Что означает аббревиатура UX?',
            options: ['User Experience', 'User Exchange', 'Universal X', 'Unit X'],
            correct: 0,
         },
      ],
      attempts: [{ userId: 1, score: 1, date: '2026-03-10' }],
   },
   {
      id: 3,
      title: 'TypeScript для начинающих',
      description: 'Изучите строгую типизацию в JavaScript.',
      authorId: 2,
      createdAt: '2026-04-05T14:00:00Z',
      views: 340,
      questions: [
         {
            id: 1,
            text: 'Какой символ используется для объявления типа в TypeScript?',
            options: [':', '=', '=>', '::'],
            correct: 0,
         },
      ],
      attempts: [],
   },
];